# Generated by Django 3.2.7 on 2023-12-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_roommember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomMember',
        ),
    ]
